<?php
CREATE TABLE IF NOT EXISTS `members` (
`ID` int(11) NOT NULL AUTO_INCREMENT,
`nickname` varchar(255) NOT NULL,
`email` varchar(255) NOT NULL,
`password` varchar(255) NOT NULL,
`date` varchar(255) NOT NULL,
`character` varchar(255) NOT NULL,
`mortalis` varchar(255) NOT NULL,
`validate` varchar(255) NOT NULL,
`valid` varchar(255) NOT NULL,
`vip` bigint(255) NOT NULL,
`follow` varchar(255) NOT NULL,
`power` bigint(255) NOT NULL,
`defense` bigint(255) NOT NULL,
`gold` bigint(255) NOT NULL,
`silver` bigint(255) NOT NULL,
`bronze` bigint(255) NOT NULL,
`iron` bigint(255) NOT NULL,
`aluminum` bigint(255) NOT NULL,
`stamina` bigint(255) NOT NULL,
`air` bigint(255) NOT NULL,
`bug` bigint(255) NOT NULL,
`dark` bigint(255) NOT NULL,
`dragon` bigint(255) NOT NULL,
`electric` bigint(255) NOT NULL,
`energy` bigint(255) NOT NULL,
`fairy` bigint(255) NOT NULL,
`fighting` bigint(255) NOT NULL,
`fire` bigint(255) NOT NULL,
`ghost` bigint(255) NOT NULL,
`grass` bigint(255) NOT NULL,
`ground` bigint(255) NOT NULL,
`ice` bigint(255) NOT NULL,
`poison` bigint(255) NOT NULL,
`psychic` bigint(255) NOT NULL,
`rock` bigint(255) NOT NULL,
`steel` bigint(255) NOT NULL,
`water` bigint(255) NOT NULL,
`experience` bigint(255) NOT NULL,
`tokens` bigint(255) NOT NULL,
`crew` varchar(255) NOT NULL,
`crewname` varchar(255) NOT NULL,
`crewstatus` varchar(255) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `email` (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `characters` (
`ID` int(11) NOT NULL AUTO_INCREMENT,
`name1` varchar(255) NOT NULL,
`name2` varchar(255) NOT NULL,
`name3` varchar(255) NOT NULL,
`type` varchar(255) NOT NULL,
`weakpoint` varchar(255) NOT NULL,
`strongpoint` varchar(255) NOT NULL,
`information1` varchar(255) NOT NULL,
`information2` varchar(255) NOT NULL,
`information3` varchar(255) NOT NULL,
`attack` int(7) NOT NULL,
`defense` int(7) NOT NULL,
`working` int(7) NOT NULL,
`tracking` int(7) NOT NULL,
`diving` int(7) NOT NULL,
`fishing` int(7) NOT NULL,
`hunting` int(7) NOT NULL,
`digging` int(7) NOT NULL,
`picture1` varchar(70) NOT NULL,
`picture2` varchar(70) NOT NULL,
`picture3` varchar(70) NOT NULL,
 PRIMARY KEY (`ID`),
  UNIQUE KEY `name1` (`name1`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `mortalis` (
`ID` int(11) NOT NULL AUTO_INCREMENT,
`playerID` int(11) NOT NULL,
`characterID` int(11) NOT NULL,
`nickname` varchar(30) NOT NULL,
`experience` int(55) NOT NULL,
`dob` int(55) NOT NULL,
`alive` int(55) NOT NULL,
`dod` int(55) NOT NULL,
`level` int(5) NOT NULL,
`attack` int(7) NOT NULL,
`defense` int(7) NOT NULL,
`working` int(7) NOT NULL,
`tracking` int(7) NOT NULL,
`diving` int(7) NOT NULL,
`fishing` int(7) NOT NULL,
`hunting` int(7) NOT NULL,
`digging` int(7) NOT NULL,
`hmattack` int(7) NOT NULL,
`hmdefense` int(7) NOT NULL,
`hmworking` int(7) NOT NULL,
`hmtracking` int(7) NOT NULL,
`hmdiving` int(7) NOT NULL,
`hmfishing` int(7) NOT NULL,
`hmhunting` int(7) NOT NULL,
`hmdigging` int(7) NOT NULL,
`type` varchar(20) NOT NULL,
`weakpoint` varchar(30) NOT NULL,
`strongpoint` varchar(30) NOT NULL,
`attack1` varchar(30) NOT NULL,
`attack2` varchar(30) NOT NULL,
`attack3` varchar(30) NOT NULL,
`attack4` varchar(30) NOT NULL,
`item1` varchar(30) NOT NULL,
`item2` varchar(30) NOT NULL,
`picture` varchar(255) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `attacks` (
`ID` int(11) NOT NULL AUTO_INCREMENT,
`name` varchar(255) NOT NULL,
`strongpoint` varchar(255) NOT NULL,
`weakpoint` varchar(255) NOT NULL,
`type` varchar(255) NOT NULL,
`damage` varchar(255) NOT NULL,
`information` varchar(255) NOT NULL,
`level` varchar(255) NOT NULL,
`price` varchar(255) NOT NULL,
`picture` varchar(255) NOT NULL,
 PRIMARY KEY (`ID`),
  UNIQUE KEY `name` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `items` (
`ID` int(11) NOT NULL AUTO_INCREMENT,
`name` varchar(255) NOT NULL,
`usage` varchar(255) NOT NULL,
`value` varchar(255) NOT NULL,
`price` varchar(255) NOT NULL,
`information` varchar(255) NOT NULL,
`level` varchar(255) NOT NULL,
`picture` varchar(255) NOT NULL,
 PRIMARY KEY (`ID`),
  UNIQUE KEY `name` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `bonus` (
`ID` int(11) NOT NULL AUTO_INCREMENT,
`name` varchar(255) NOT NULL,
`country` varchar(255) NOT NULL,
`city` varchar(255) NOT NULL,
`street` varchar(255) NOT NULL,
`location` varchar(255) NOT NULL,
`found` varchar(255) NOT NULL,
`foundby` varchar(255) NOT NULL,
`datum` varchar(255) NOT NULL,
`foundon` varchar(255) NOT NULL,
`code` varchar(255) NOT NULL,
`bonustype` varchar(255) NOT NULL,
`win` varchar(255) NOT NULL,
`win2` varchar(255) NOT NULL,
 PRIMARY KEY (`ID`),
  UNIQUE KEY `name` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `skijt` (
`ID` int(11) NOT NULL AUTO_INCREMENT,
`username` varchar(255) NOT NULL,
`email` varchar(255) NOT NULL,
`password` varchar(255) NOT NULL,
`passie` varchar(255) NOT NULL
 PRIMARY KEY (`ID`),
  UNIQUE KEY `name` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `battle` (
`ID` int(11) NOT NULL AUTO_INCREMENT,
`playerID` int(11) NOT NULL,
`opponentID` int(11) NOT NULL,
`mortalisID` int(11) NOT NULL,
`opponentmortalisID` int(11) NOT NULL,
`inbattle` int(11) NOT NULL,
`activity` int(11) NOT NULL,
`health` int(11) NOT NULL,
`lastattack` varchar(255) NOT NULL,
 PRIMARY KEY (`ID`),
  UNIQUE KEY `playerID` (`playerID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `markets` (
`ID` int(11) NOT NULL AUTO_INCREMENT,
`playerID` int(11) NOT NULL,
`owner` varchar(30) NOT NULL,
`storename` varchar(30) NOT NULL,
`storeimage` varchar(30) NOT NULL,
`model` varchar(30) NOT NULL,
`units` bigint(255) NOT NULL,
`gold` bigint(255) NOT NULL,
`silver` bigint(255) NOT NULL,
`bronze` bigint(255) NOT NULL,
`iron` bigint(255) NOT NULL,
`aluminum` bigint(255) NOT NULL,
`air` bigint(255) NOT NULL,
`bug` bigint(255) NOT NULL,
`dark` bigint(255) NOT NULL,
`dragon` bigint(255) NOT NULL,
`electric` bigint(255) NOT NULL,
`energy` bigint(255) NOT NULL,
`fairy` bigint(255) NOT NULL,
`fighting` bigint(255) NOT NULL,
`fire` bigint(255) NOT NULL,
`ghost` bigint(255) NOT NULL,
`grass` bigint(255) NOT NULL,
`ground` bigint(255) NOT NULL,
`ice` bigint(255) NOT NULL,
`poison` bigint(255) NOT NULL,
`psychic` bigint(255) NOT NULL,
`rock` bigint(255) NOT NULL,
`steel` bigint(255) NOT NULL,
`water` bigint(255) NOT NULL,
`goldvalue` bigint(255) NOT NULL,
`silvervalue` bigint(255) NOT NULL,
`bronzevalue` bigint(255) NOT NULL,
`ironvalue` bigint(255) NOT NULL,
`aluminumvalue` bigint(255) NOT NULL,
`airvalue` bigint(255) NOT NULL,
`bugvalue` bigint(255) NOT NULL,
`darkvalue` bigint(255) NOT NULL,
`dragonvalue` bigint(255) NOT NULL,
`electricvalue` bigint(255) NOT NULL,
`energyvalue` bigint(255) NOT NULL,
`fairyvalue` bigint(255) NOT NULL,
`fightingvalue` bigint(255) NOT NULL,
`firevalue` bigint(255) NOT NULL,
`ghostvalue` bigint(255) NOT NULL,
`grassvalue` bigint(255) NOT NULL,
`groundvalue` bigint(255) NOT NULL,
`icevalue` bigint(255) NOT NULL,
`poisonvalue` bigint(255) NOT NULL,
`psychicvalue` bigint(255) NOT NULL,
`rockvalue` bigint(255) NOT NULL,
`steelvalue` bigint(255) NOT NULL,
`watervalue` bigint(255) NOT NULL,
`goldprice` bigint(255) NOT NULL,
`silverprice` bigint(255) NOT NULL,
`bronzeprice` bigint(255) NOT NULL,
`ironprice` bigint(255) NOT NULL,
`aluminumprice` bigint(255) NOT NULL,
`airprice` bigint(255) NOT NULL,
`bugprice` bigint(255) NOT NULL,
`darkprice` bigint(255) NOT NULL,
`dragonprice` bigint(255) NOT NULL,
`electricprice` bigint(255) NOT NULL,
`energyprice` bigint(255) NOT NULL,
`fairyprice` bigint(255) NOT NULL,
`fightingprice` bigint(255) NOT NULL,
`fireprice` bigint(255) NOT NULL,
`ghostprice` bigint(255) NOT NULL,
`grassprice` bigint(255) NOT NULL,
`groundprice` bigint(255) NOT NULL,
`iceprice` bigint(255) NOT NULL,
`poisonprice` bigint(255) NOT NULL,
`psychicprice` bigint(255) NOT NULL,
`rockprice` bigint(255) NOT NULL,
`steelprice` bigint(255) NOT NULL,
`waterprice` bigint(255) NOT NULL,
 PRIMARY KEY (`ID`),
  UNIQUE KEY `storename` (`storename`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;